server:
  port: 8083

spring:
  ai:
    zhipuai:
      api-key: "0ded7b94d4e3470a938685cfade1fc10.73OIOnuY6gsqPG14"  # 配置 API Key
      base-url: "https://open.bigmodel.cn/api/paas"   # 配置 模型地址
      chat:
        options:
          model: glm-4.5