server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lfcpj?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-circular-references: true

#  kafka:
#    #以逗号分隔的主机：端口对列表，用于建立与Kafka的连接
#    bootstrap-servers: 192.168.1.54:9092
#    producer:
#      # 发生错误后，消息重发的次数。
#      retries: 0
#      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
#      batch-size: 16384
#      # 设置生产者内存缓冲区的大小。
#      buffer-memory: 33554432
#      # 键的序列化方式
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      # 值的序列化方式
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: 1
#    consumer:
#      # 键的反序列化方式
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      # 值的反序列化方式
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id

send-msg-conf:
  mysql-as-mq : true
  open-cache: true
  max-retry-count: 5
  email-host: smtp.qq.com
  email-port: 587
  #替换为自己的
  email-account: 770995260@qq.com
  #替换为自己的
  email-auth-code: xrgfesynlkvcbbie